environment: aws
# environment: 'aws'

common:

#  maf_downloader:
#    url_base: 'http://hgdownload.cse.ucsc.edu/goldenPath/galGal6/multiz77way/maf/'
#    file_name_head: chr
#    file_name_tail: .maf.gz

  aws_s3:
    key: 'null'
    secret: 'null'
    bucket_name: aves-multiz77way
#    remote_maf_base_path: "download/multiz77way"
#    remote_file_name_head: chr
#    remote_file_name_tail: .maf.gz
    remote_chr_maf_base_path: "preparation/sarcopterygii"

  maf_reader:
    maf_ref_specie: galGal6
    maf_aln_species: #not including reference specie
      - allMis1
      - cheMyd1
      - chrPic2
      - pelSin1
      - apaSpi1
      - anoCar2
      - xenTro9
#  maf_joiner:
#    out_file_name_head:
#    out_file_name_tail:


local:

#  maf_downloader:
#    local_output_directory: '/paula/2019/aves/data/raw_maf'
#
#  aws_s3:

  maf_reader:
    local_input_directory: '/paula/2019/aves/data/raw_maf'
    local_output_directory: '/paula/2019/aves/data/clean_maf_sarcopterygii'


aws:

#  maf_downloader:
#    local_output_directory: '/home/rstudio/2019/aves/data/raw_maf'
#
#  aws_s3:

  maf_reader:
    local_input_directory: '/home/rstudio/disco_tmp/aves/data/raw_maf'
    local_output_directory: '/home/rstudio/disco_tmp/aves/data/clean_maf_sarcopterygii'

